modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/SlimeKnights/Hilt/issues"
logoFile="Hilt.png"
license="MIT"

[[mixins]]
    config="hilt.mixins.json"

[[mods]]
    modId="hilt"
    version="${version}"
    displayName="Hilt"
    authors="Slime Knights"
    description='''
Shared code for Slime Knights mods and others.
    '''
    displayURL="https://minecraft.curseforge.com/projects/hilt"

[[dependencies.hilt]]
    modId="neoforge"
    type="required"
    versionRange="${neo_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.hilt]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
